### PR TITLE
Add note to the read me file plus metadata addition

### PR DESCRIPTION
**Pull request by amd-jnovotny**
Added a note to the readme file pointing to the official documentation. Also added missing metadata information to the license file.

### CODE REVIEW

**Review by cgmillette — APPROVED** [review]
lgtm!

**Comment by cgmillette** [comment]
@amd-jnovotny does this need a promotion to rocm 6.3 ?

**Comment by amd-jnovotny** [comment]
@cgmillette : I don't think it necessarily needs to be backported. Most users will look at the develop branch of the GitHub and see the note there. The metadata fixes are only required to be in place for 6.4. But if you want this one backported to the 6.3 release branch, let me know and I will do so once the release branch is created.

**Comment by cgmillette** [comment]
> @cgmillette : I don't think it necessarily needs to be backported. Most users will look at the develop branch of the GitHub and see the note there. The metadata fixes are only required to be in place for 6.4. But if you want this one backported to the 6.3 release branch, let me know and I will do so once the release branch is created.

Ok, we're all good then! Nothing more needed

**Pull request merged**
